eventespresso/actions

.github/workflows/build-packages.yml, packages/makepot/README.md, packages/makepot/src/utils.ts
This PR creates the build workflow for `main` branch. Whenever a commit is pushed to master it builds the packages into `lib` and `dist` directories.
=> Build packages workflow

.eslintrc.json, .github/workflows/build-pr.yml, packages/makepot/README.md
This PR adds build test for PRs.
=> Add PR build workflow

package.json, packages/version-bump/src/main.ts, packages/version-bump/src/tests/main.test.ts, packages/version-bump/src/tests/utils.ts, packages/version-bump/src/utils.ts, yarn.lock
This PR adds 30+ normal and 50+ edge test cases for version bump action
=> Add test cases for version bump

packages/version-bump/action.yml, packages/version-bump/src/main.ts, packages/version-bump/src/tests/main.test.ts, packages/version-bump/src/tests/utils.test.ts, packages/version-bump/src/tests/utils.ts, packages/version-bump/src/utils.ts
This PR refactors version bump action to simplify the logic and use SRP for the input passed as mentioned in [this comment](https://github.com/eventespresso/barista/issues/271#issuecomment-728211584)
=> Version bump refactor action

packages/checkout-and-LAMP/README.md, packages/checkout-and-LAMP/action.yml, packages/install-wp-tests/action.yml
This PR extracts the initial checkout and LAMP stack set up steps in GitHub actions workflows and makes them reusable as a single action using the new `composite` API of GitHub actions.
=> Extract and consilidate checkout and LAMP setup action

packages/auto-pr-labeler/action.yml
had incorrect path in `action.yml`, need to push branch so that assets get rebuilt properly
=> Fix Auto-PR-Labeler Path

packages/auto-pr-labeler/src/index.ts
also needed to fix an import and push branch to rebuild assets properly
=> Fix Auto PR Labeler Import

packages/auto-pr-labeler/src/index.ts, packages/auto-pr-labeler/src/mutations.ts
=> Add try catch Inside assignStatusLabels()

packages/auto-pr-labeler/src/index.ts
another PR to fix issue and trigger asset rebuild
=> Fix Input Name

packages/auto-pr-labeler/src/index.ts, packages/auto-pr-labeler/src/mutations.ts, packages/auto-pr-labeler/src/queries.ts, packages/auto-pr-labeler/src/utils.ts
Hopefully this fixes the authentication issues.
needed a PR so that dist assets get rebuilt
=> Improve/Fix Headers

packages/auto-pr-labeler/src/queries.ts
oops... forgot to update `org` to `owner`
=> Update Query Variable

packages/auto-pr-labeler/src/mutations.ts, packages/auto-pr-labeler/src/queries.ts
still getting this error:
```
(node:1732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. 
This error originated either by throwing inside of an async function without a catch block, 
or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```
on the bright side... authentication _seems_ to be working
=> Use try-catch Everywhere

packages/auto-pr-labeler/src/index.ts, packages/auto-pr-labeler/src/mutations.ts, packages/auto-pr-labeler/src/queries.ts
ok try it without try catch blocks everywhere
=> DONT Use try-catch Everywhere!

packages/auto-pr-labeler/src/mutations.ts, packages/auto-pr-labeler/src/queries.ts, packages/auto-pr-labeler/src/utils.ts
try passing query vars & headers directly to queries and mutations instead of using `graphql.defaults`
=> Try Direct Query Vars

packages/auto-pr-labeler/action.yml, packages/auto-pr-labeler/src/utils.ts
need PR to rebuild dist assets
=> Rename `org` Var to `owner`

package.json, packages/auto-pr-labeler/action.yml, packages/auto-pr-labeler/src/index.ts, packages/auto-pr-labeler/src/utils.ts, yarn.lock
found this page: https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
and discovered that we can potentially get ALL of the event parameters directly
=> Use `env` Vars

packages/auto-pr-labeler/src/utils.ts
=> Update Event Var Source

package.json, packages/auto-pr-labeler/action.yml, packages/auto-pr-labeler/src/utils.ts, yarn.lock
- env vars only work where PR is triggered
- return to getting vars from inputs
=> Get Vars From Inputs

packages/auto-pr-labeler/action.yml, packages/auto-pr-labeler/src/index.ts, packages/auto-pr-labeler/src/queries.ts, packages/auto-pr-labeler/src/utils.ts
- revert to using separate owner & repo input vars 
- revert to using async for queries
=> Fix `getPullRequest()` Query

packages/e2e-tests/README.md
=> Update README.md for package e2e-tests

.nvmrc, package.json, packages/auto-pr-labeler/action.yml, packages/auto-pr-labeler/package.json, packages/checkout-and-yarn/action.yml, packages/e2e-tests/action.yml, packages/e2e-tests/package.json, packages/e2e-tests/src/Artifact.ts, packages/e2e-tests/src/Browsers.ts, packages/e2e-tests/src/Docker.ts, packages/io/package.json, packages/json-prop/action.yml, packages/json-prop/package.json, packages/makepot/action.yml, packages/makepot/package.json, packages/multi-changelog/action.yml, packages/multi-changelog/package.json, packages/remove-files/action.yml, packages/remove-files/package.json, packages/utils/package.json, packages/version-bump/action.yml, packages/version-bump/package.json, yarn.lock
=> Package "@action/artifact@v1" is getting deprecated on June 30, 2024
